name: arbbot-analytics-api
region: fra
services:
- name: api
  github:
    repo: your-username/arbbot-analytics-api
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
  envs:
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: DB_HOST
    scope: RUN_TIME
    value: db-postgresql-fra1-54201-do-user-1252164-0.h.db.ondigitalocean.com
  - key: DB_PORT
    scope: RUN_TIME
    value: "25060"
  - key: DB_NAME
    scope: RUN_TIME
    value: bot_activity
  - key: DB_USER
    scope: RUN_TIME
    value: bot
  - key: DB_PASSWORD
    scope: RUN_TIME
    type: SECRET
    value: LOGGERDB_PW
  - key: DB_SSL
    scope: RUN_TIME
    value: "true"
